### ISSUE TITLE
Clippy warns against implementing `Into`

### ISSUE THREAD

**Issue by Rafferty97** [Lukas3674/rust-bitmask-enum#1]
I am using this crate in my project simply as so:

```
#[bitmask(u8)]
pub enum ArrowDirection {
    Left,
    Straight,
    Right
}
```

However clippy is warning against implementing `Into` directly, suggesting to implement `From` instead as it gives you `Into` for free (`clippy::from_over_into`). I had a quick look at the source code and it seems you'd just need to remove the `Into` implementation to resolve this lint error.

**Comment by Lukas3674** [comment]
You are completely right, don't know why I did that back then, will fix it when I get back home!

**Comment by Lukas3674** [comment]
I just realized that they are not the same, the From implementation was for `From<u8> for Bitmask` and the Into implementation was for `Into<u8> for Bitmask`. But because it is better to implement From instead of Into, I replaced the Into implementation into a From implementation e.g. `From<Bitmask> for u8` instead of `Into<u8> for Bitmask`.
