### ISSUE TITLE
Config in bitmask attribute instead of separate?

### ISSUE THREAD

**Issue by devnev** [Lukas3674/rust-bitmask-enum#15]
This isn't necessarily an issue, more of a design question / rust noob question (maybe a feature request), I hope thats OK.

I was wondering, why use a separate attribute for the bitmask_config flags, instead of allowing them in the bitmask attribute? E.g.
```rust
#[bitmask(u8, vec_debug)]
```

If allowing that is of interest, I'd be happy to have a go at implementing it.

**Comment by Lukas3674** [comment]
I believe I made that decision because I didn't like the way the values in the macro had to be parsed:
- Is it allowed to only have config options without a type?
- Can the type be anywhere in the list of config options?

Right now, it is straightforward; any value in the `bitmask` macro is the type, while the list of values in the `bitmask_config` macro are config options, which is very easy to parse.

Thoughts that existed before were exactly the way you mention and something like this:
```rust
#[bitmask(u8, options = [vec_debug])]
```

But I don't think I want multiple ways to specify config options, and I don't want to remove the way it is done right now because it would be a breaking change, and I don't have the time right now to think about what other ways there are and how to implement them.

Sorry to say this, but I don't think I want to make any changes to this crate right now.
But thank you for your interest, and feel free to ask any more questions if your goal is to learn how Rust proc macros work.

**Comment by devnev** [comment]
Thanks for the very clear response.

And as it stands, this crate already feels like a nicely concise and practical example for getting started with proc macros.
