### ISSUE TITLE
Naming of the `::all()` and `::full()` methods

### ISSUE THREAD

**Issue by DCNick3** [Lukas3674/rust-bitmask-enum#16]
In my opinion the distinction between the `::all()` and `::full()` methods is not clear from the name. My initial guesses for what they do was backwards even: `all` kind of stands for all enum variants, while `full` stands for full int width.

There's some previous art there: [rust-bitmask-enum](https://github.com/Lukas3674/rust-bitmask-enum) uses `all` to mean "all variants" (and doesn't seem to provide an "all bits" constructor).

I think a better naming would be:

- `all`: sets all variants
- `all_bits`: sets all bits

What are you thoughts on this API? I can make a PR if you want

**Comment by Lukas3674** [comment]
So the reason for this API in the first place was because `all` existed before `full`, and I didn't want to do a breaking change that might not even be noticed by tests. But in general, I have the same opinion: `full` is more like full bits, and `all` is more like all variants, which is the opposite way it is now.

But like I said, just swapping the behaviour would not only be a breaking change, but it might not even be noticed if someone relies on this behaviour. So the only way I see of changing this is by deprecating both `all` and `full` with `#[deprecated(since="x.y.z", note="please use ...")]`, and creating two new methods that specify their behavior better, such as `all_bits` and `all_variants` or something like it.

**Comment by Lukas3674** [comment]
If you want to implement that, feel free; otherwise, I will do it.
And because the `#[deprecated]` macro only issues warnings, I think I can publish it as a new patch version together with your other changes that I just merged.
