### ISSUE TITLE
Make the #[bitmask(type)] macro more benevolent to what the 'type' can be

### ISSUE THREAD

**Issue by tomaspecl** [Lukas3674/rust-bitmask-enum#4]
I have a use case like this:
```
type ButtonsSize = u16;
#[bitmask(ButtonsSize)]
pub enum Buttons { ... }
```
And then I later have code that uses ButtonsSize:
```
fn serialize<S: serde::Serializer>(data: &Buttons, serializer: S) -> Result<S::Ok, S::Error> {
    data.bits().serialize(serializer)
}
fn deserialize<'de, D: serde::Deserializer<'de>>(deserializer: D) -> Result<Buttons, D::Error> {
    Ok(Buttons {
        bits: ButtonsSize::deserialize(deserializer)?,
    })
}
```
But it gives me this error:
```
#[bitmask(ButtonsSize)]
| ^^^^^^^^^^^^^^^^^^^^^^^
|
= help: message: type can only be an (un)signed integer.
```
I can use this instead but it is not as convenient:
```
type ButtonsSize = u16;
#[bitmask(u16)]
pub enum Buttons { ... }
```

I do not have much experience with proc_macros so I am not sure if I could make it work myself and do a pull request. But if you dont have time to code it then just tell me and I could try to do it.

**Comment by Lukas3674** [comment]
I could just remove the check for only (un)signed integer types, this will make an alias using `type` work, but will give an ugly error when using it with a non integer type. Don't think there is a way to differentiate between type aliases of (un)signed integer types and any other type!

Using anything but an (un)signed integer type (or an alias of an (un)signed integer type) will never work, because of the implementation.

~~I don't think I mind changing it so that it allows aliases, but I would prefer it if there was a way to differentiate between type aliases of (un)signed integer types and any other type.~~

~~Will think about it and maybe push a new version.~~

**Comment by Lukas3674** [comment]
I will not make this change, because the only thing affected is the macro invocation `#[bitmask(...)]` and the documentation. There are no real changes because it will only allow an alias, and not a real type.

**Comment by Lukas3674** [comment]
If you want a way to modify the macro to allow any types, not just aliases, then you are free to ask and fork the repo. But I think it will be a lot simpler to just write a custom enum or bitmask instead of modifying this macro.

**Comment by Lukas3674** [comment]
If you only want to allow aliases in a fork, the only place you have to change is the function `parse_typ` to the following:

```rust
fn parse_typ(attr: TokenStream) -> Ident {
    if attr.is_empty() {
        Ident::new("usize", Span::call_site().into())
    } else {
        syn::parse::<Ident>(attr).expect("(un)signed interger or alias")
    }
}
```

This will obviously make it possible to use the identifier of a struct or any other type, leading to the previously mentioned ugly error.

**Comment by tomaspecl** [comment]
Can you not somehow get the underlying type from the type Alias and check it instead? Because inside your macro you are converting the Token into a String and so I was thinking if it would be possible to first get the real type name out of the Token (if its possible) and then compare it as a String.

**Comment by Lukas3674** [comment]
If you find a way to do that then it would be fine, but I am not aware that it is possible.
