### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by xamgore** [Lukas3674/rust-bitmask-enum#5]
Thank you so much for the crate! I love the design though I've encountered a problem. I would like to parse `u8` into a bitmask. What is the expected way to do that?

**Comment by Lukas3674** [comment]
There shouldn't be any problem, just make sure, that if you are using the `derive` feature, you do the `derive` after the `bitmask` macro.
Something like this:
```rust
use bitmask_enum::bitmask;
use serde::{Serialize, Deserialize};
use serde_json::{from_str, to_string};

#[bitmask(u8)]
#[derive(Serialize, Deserialize)]
enum Bitmask {
    A,
}

fn main() {
    let a = Bitmask::A;
    let json = to_string(&a).unwrap();
    println!("{:?}", json);
    assert!(from_str::<Bitmask>(&json).unwrap() == a);
}
```

**Comment by Lukas3674** [comment]
If you don't use the `derive` feature, be aware that the enum is transformed into a struct with a single `bits` field of the specified type, nothing else. That is the only thing you will have to serialize / deserialize.

**Comment by xamgore** [comment]
Wow, that was a fast response. Thank you! 😍 ❤️ 

It works, indeed. I had checked the macro's expansion code and was sure `#[derive(Serialize, Deserialize)]` are attached to the rest attributes. Why should the `#[bitmask(u8)]` attribute be above?

```rust
#(#attr)*
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#vis struct #ident {
    bits: #typ,
}
```

**Comment by Lukas3674** [comment]
> Why should the `#[bitmask(u8)]` attribute be above?

Because of how rust expands macros.
The first macro basically consumes everything that follows it  (entire struct, enum, ...).

In this example:
```rust
#[bitmask(u8)]
#[derive(Serialize, Deserialize)]
enum Bitmask {
    A,
}
```
it will expand to something like:
```rust
#[derive(Serialize, Deserialize)]
struct Bitmask {
    bits: u8,
}
```
meaning the serde `Serialize` and `Deserialize` are derived after the conversion to a `struct`.

If we have it the other way around, the serde `Serialize` and `Deserialize` are derived before the conversion to a `struct`,
leading to an error, because the expansion will then look like this:
```rust
impl Serialize for Bitmask {
    // ... implementation for enum Bitmask { A }
}
impl Deserialize for Bitmask {
    // ... implementation for enum Bitmask { A }
}
#[bitmask(u8)]
enum Bitmask {
    A,
}
```
afterwards the `#[bitmask]` macro will convert the `enum` to the aforementioned `struct`, leading to an error,
because the `impl` of `Serialize` and `Deserialize` do not match the new `struct`.

Hope that is understandable :)
